// [
//   "right_leg_lower",
//   "left_leg_lower",
//   "right_hand",
//   "right_arm",
//   "right_shoulder",
//   "left_hand",
//   "left_arm",
//   "left_shoulder",
//   "head",
//   "chest",
//   "stomach",
//   "foot"
// ];

export const mockMedicalDocument = {
  category: "Medical document",
  events: [
    {
      disease: "Hypertension",
      chronic: true,
      medication: ["Amlodipine", "Lisinopril"],
      body_part: ["right_arm"],
      date_time: "2022-07-15 08:30",
    },
    {
      disease: "Type 2 Diabetes",
      chronic: true,
      medication: ["Metformin"],
      body_part: ["right_leg_lower"],
      date_time: "2021-11-10 14:45",
    },
    {
      disease: "Fractured Wrist",
      chronic: false,
      medication: ["Ibuprofen"],
      body_part: ["left_hand"],
      date_time: "2023-02-03 12:20",
    },
    {
      disease: "Asthma",
      chronic: true,
      medication: ["Albuterol Inhaler"],
      body_part: [],
      date_time: "2020-06-22 07:00",
    },
    {
      disease: "Seasonal Allergies",
      chronic: false,
      medication: ["Cetirizine"],
      body_part: [],
      date_time: "2024-04-10 09:30",
    },
    {
      disease: "Migraine",
      chronic: true,
      medication: ["Sumatriptan"],
      body_part: ["head"],
      date_time: "2023-05-22 14:00",
    },
    {
      disease: "Chronic Bronchitis",
      chronic: true,
      medication: ["Prednisone"],
      body_part: ["chest"],
      date_time: "2021-12-17 08:00",
    },
    {
      disease: "Fractured Ankle",
      chronic: false,
      medication: ["Codeine"],
      body_part: ["foot"],
      date_time: "2022-09-14 10:45",
    },
    {
      disease: "Eczema",
      chronic: true,
      medication: ["Hydrocortisone Cream"],
      body_part: ["left_leg_upper"],
      date_time: "2023-03-05 16:10",
    },
    {
      disease: "Gastric Ulcer",
      chronic: false,
      medication: ["Omeprazole"],
      body_part: ["stomach"],
      date_time: "2022-08-22 13:50",
    },
    {
      disease: "Osteoarthritis",
      chronic: true,
      medication: ["Naproxen"],
      body_part: ["right_leg_lower"],
      date_time: "2023-07-02 11:30",
    },
    {
      disease: "Carpal Tunnel Syndrome",
      chronic: true,
      medication: ["Ibuprofen"],
      body_part: ["right_hand"],
      date_time: "2021-10-28 15:40",
    },
    {
      disease: "Tennis Elbow",
      chronic: false,
      medication: ["Physical Therapy"],
      body_part: ["left_arm"],
      date_time: "2023-01-20 10:00",
    },
    {
      disease: "Bacterial Pneumonia",
      chronic: false,
      medication: ["Amoxicillin"],
      body_part: ["chest"],
      date_time: "2022-04-15 09:45",
    },
    {
      disease: "Chronic Sinusitis",
      chronic: true,
      medication: ["Nasal Spray", "Steroid"],
      body_part: ["head"],
      date_time: "2021-09-12 17:20",
    },
    {
      disease: "Torn Ligament",
      chronic: false,
      medication: ["Painkillers", "Surgery"],
      body_part: ["right_leg_upper"],
      date_time: "2024-03-14 11:25",
    },
    {
      disease: "Sciatica",
      chronic: true,
      medication: ["Gabapentin"],
      body_part: ["left_leg_lower", "left_leg_upper"],
      date_time: "2022-06-25 13:00",
    },
    {
      disease: "Rotator Cuff Tear",
      chronic: false,
      medication: ["Surgery", "Rehabilitation"],
      body_part: ["left_shoulder"],
      date_time: "2021-08-19 08:50",
    },
    {
      disease: "Chronic Kidney Disease",
      chronic: true,
      medication: ["Lisinopril", "Water Pills"],
      body_part: ["stomach"],
      date_time: "2021-11-05 07:40",
    },
  ],
};
