import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthWrapper from "./components/wrappers/auth-wrapper";
import PageWrapper from "./components/wrappers/page-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthWrapper>
      <html lang="en">
        <body className={`${inter.className}  h-full relative`}>
          <div className="absolute inset-0 -z-10 h-full w-full bg-white bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]">
            <div className="absolute left-0 -right-3/4 top-1/4 -z-10 m-auto h-[310px] w-[310px] rounded-full bg-blue-400 opacity-30 blur-[100px]"></div>
            <div className="absolute -left-[110%] right-0 bottom-1/4 -z-10 m-auto h-[310px] w-[310px] rounded-full bg-blue-400 opacity-30 blur-[100px]"></div>
          </div>
          <PageWrapper>
            {children}
            {/* <Toaster/> */}
          </PageWrapper>
        </body>
      </html>
    </AuthWrapper>
  );
}
