import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthWrapper from "./components/wrappers/auth-wrapper";
import PageWrapper from "./components/wrappers/page-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthWrapper>
      <html lang="en">
        <body className={inter.className}>
          <PageWrapper>
            {children}
            {/* <Toaster/> */}
          </PageWrapper>
        </body>
      </html>
    </AuthWrapper>
  );
}
